@api = http://localhost:3000

### Get all products
GET {{api}}/productos

### Get a product by id
GET {{api}}/productos/19

### Get all products by category
GET {{api}}/productos/categoria/gatos

### Get all products by subcategory
GET {{api}}/productos/subcategoria/alimentos

### Get all products by provider
GET {{api}}/productos/proveedor/PetWorld

### Get all products by if perishes
GET {{api}}/productos/perece/si

### Get all products by max days before perish
GET {{api}}/productos/dias-perece/10