@api = http://localhost:3000

### Get all products
GET {{api}}/productos

### Get all products by category
GET {{api}}/productos/categoria/gatos

### Get all products by subcategory
GET {{api}}/productos/subcategoria/alimentos